spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}
app:
  lunaToken: ${LUNA_TOKEN}
  notifyPeriod: ${NOTIFY_PERIOD}